#!/bin/bash
#SBATCH --account=PAS1906
#SBATCH --cluster=owens
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=28
#SBATCH --time=00:15:00
#SBATCH --job-name=lab3

export DATAFILE='PC_data_t05000'
export EXECFILE='lab3_mengfan_zhu.2420'

echo job started at `date`
echo on compute node `cat ${PBS_NODEFILE}`

cd ${SLURM_SUBMIT_DIR}
# /users/PAS1906/mengfan/CSE_5441/test3
cp ${DATAFILE} ${TMPDIR}
cd ${TMPDIR}
echo ${EXECFILE} ${DATAFILE}  >>current.out
echo job started at `date` >>current.out
time ${SLURM_SUBMIT_DIR}/${EXECFILE} <${DATAFILE}  >>current.out 2>&1
echo job ended at `date` >>current.out

export SAVEDIR=${SLURM_SUBMIT_DIR}'/results'
# mkdir ${SAVEDIR}
rename current.out ${PBS_JOBID}.out
mv ${PBS_JOBID}.out ${SAVEDIR}
